### ISSUE TITLE
缺少datasets文件

### ISSUE THREAD

**Issue by lzy-whut** [Captain-Hong/SFUDA_AOS#1]
![image](https://user-images.githubusercontent.com/58968914/218054743-e028faaf-4c58-4548-aa33-f80b2d796e75.png)

**Comment by Captain-Hong** [comment]
corrected

**Comment by lzy-whut** [comment]
> correct
方便提供下吗？

**Comment by Captain-Hong** [comment]
已经提供了
        
    
        
            
        
    
    
        
        

        
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月10日 19:11
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Captain-Hong/SFUDA_AOS] 缺少datasets文件 (Issue #1)
        
      
    
  
  



correct

方便提供下吗？
